/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as RulersRouteImport } from './routes/rulers'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as IrrigationRouteImport } from './routes/irrigation'
import { Route as InscriptionsRouteImport } from './routes/inscriptions'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DynastyRouteImport } from './routes/dynasty'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RulersRoute = RulersRouteImport.update({
  id: '/rulers',
  path: '/rulers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationRoute = IrrigationRouteImport.update({
  id: '/irrigation',
  path: '/irrigation',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionsRoute = InscriptionsRouteImport.update({
  id: '/inscriptions',
  path: '/inscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DynastyRoute = DynastyRouteImport.update({
  id: '/dynasty',
  path: '/dynasty',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dynasty': typeof DynastyRoute
  '/gallery': typeof GalleryRoute
  '/inscriptions': typeof InscriptionsRoute
  '/irrigation': typeof IrrigationRoute
  '/maps': typeof MapsRoute
  '/research': typeof ResearchRoute
  '/rulers': typeof RulersRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dynasty': typeof DynastyRoute
  '/gallery': typeof GalleryRoute
  '/inscriptions': typeof InscriptionsRoute
  '/irrigation': typeof IrrigationRoute
  '/maps': typeof MapsRoute
  '/research': typeof ResearchRoute
  '/rulers': typeof RulersRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/dynasty': typeof DynastyRoute
  '/gallery': typeof GalleryRoute
  '/inscriptions': typeof InscriptionsRoute
  '/irrigation': typeof IrrigationRoute
  '/maps': typeof MapsRoute
  '/research': typeof ResearchRoute
  '/rulers': typeof RulersRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/dynasty'
    | '/gallery'
    | '/inscriptions'
    | '/irrigation'
    | '/maps'
    | '/research'
    | '/rulers'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/dynasty'
    | '/gallery'
    | '/inscriptions'
    | '/irrigation'
    | '/maps'
    | '/research'
    | '/rulers'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/dynasty'
    | '/gallery'
    | '/inscriptions'
    | '/irrigation'
    | '/maps'
    | '/research'
    | '/rulers'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DynastyRoute: typeof DynastyRoute
  GalleryRoute: typeof GalleryRoute
  InscriptionsRoute: typeof InscriptionsRoute
  IrrigationRoute: typeof IrrigationRoute
  MapsRoute: typeof MapsRoute
  ResearchRoute: typeof ResearchRoute
  RulersRoute: typeof RulersRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rulers': {
      id: '/rulers'
      path: '/rulers'
      fullPath: '/rulers'
      preLoaderRoute: typeof RulersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation': {
      id: '/irrigation'
      path: '/irrigation'
      fullPath: '/irrigation'
      preLoaderRoute: typeof IrrigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscriptions': {
      id: '/inscriptions'
      path: '/inscriptions'
      fullPath: '/inscriptions'
      preLoaderRoute: typeof InscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynasty': {
      id: '/dynasty'
      path: '/dynasty'
      fullPath: '/dynasty'
      preLoaderRoute: typeof DynastyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DynastyRoute: DynastyRoute,
  GalleryRoute: GalleryRoute,
  InscriptionsRoute: InscriptionsRoute,
  IrrigationRoute: IrrigationRoute,
  MapsRoute: MapsRoute,
  ResearchRoute: ResearchRoute,
  RulersRoute: RulersRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
